#AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = ['power']

#Cell
def power(a,b):
    # a^b
    if b==0:
        return a
    elif b%2==1:
        return power(a,b-1)*a
    else:
        return power(a,b/2)*power(a,b/2)